server:
  port: 19550
  servlet:
    context-path: /api
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sandauactivity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yishiyile

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 300

  servlet:
    multipart:
      max-file-size: 4MB
