server:
  port: 19550
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sandauactivity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yishiyile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 300

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java